~/utilities/MOPAC_Batch.csh "(15-Crown-5)-(nitrato-O,O')-sodium (JAKCUT).mop"
~/utilities/MOPAC_Batch.csh "(15-Crown-5)-(perchlorato-O,O')-sodium (KAPDUA).mop"
~/utilities/MOPAC_Batch.csh "(15-Crown-5)-diaqua-cobalt tetrachloro-copper(ii) (JUSGAF).mop"
~/utilities/MOPAC_Batch.csh "(15-Crown-5)-trichloro-lanthanum(iii) (YICCES).mop"
~/utilities/MOPAC_Batch.csh "(15-Crown-5)-trichloro-tellurium hexachloro-antimony (KUHXOA).mop"
~/utilities/MOPAC_Batch.csh "(18-Crown-6)-bis(nitrato-O,O')-strontium (JAWWAF).mop"
~/utilities/MOPAC_Batch.csh "(18-Crown-6)-bis(perchlorato)-barium (MIFNUL).mop"
~/utilities/MOPAC_Batch.csh "(18-Crown-6)-di-iodo-thallium tetra-iodo-thallium (ZEZFAL).mop"
~/utilities/MOPAC_Batch.csh "(18-Crown-6)-diaqua-bromo-rubidium(i) (XAJXUD).mop"
~/utilities/MOPAC_Batch.csh "(18-Crown-6)-potassium bis(Chloro-(2,3,4,5-tetramethylphospholyl-P)-indium) (JEZDUN).mop"
~/utilities/MOPAC_Batch.csh "(18-Crown-6)-potassium bis(pyridine)-tetrakis(isothiocyanato)-indium(iii) pyridine solvate (YUXXIY).mop"
~/utilities/MOPAC_Batch.csh "(18-Crown-6)-potassium bis(trifluoromethyl)-iodo-mercury (AQEPIV).mop"
~/utilities/MOPAC_Batch.csh "(18-Crown-6)-rubidium tetrachloro-gold(iii) (DONYOU).mop"
~/utilities/MOPAC_Batch.csh "(18-Crown-6)-rubidium tetracyano-gold(iii) (DONYUA).mop"
~/utilities/MOPAC_Batch.csh "(18-Crown-6-potassium) (h5-cyclopentadienyl)-(h7-heptatrienyl)-niobium (KOSMEK).mop"
~/utilities/MOPAC_Batch.csh "(4,4-bipyridinedi-ium) 4,4-bipyridinium hexabromo-antimony(iii) (DOSYAM).mop"
~/utilities/MOPAC_Batch.csh "(5-Carboxy-1H-imidazole-4-carboxylato)-diammine-silver(i) (DUKMOM).mop"
~/utilities/MOPAC_Batch.csh "(6-Methyl-2-pyridinecarboxylato-N,O)-(6-methyl-2-pyridinecarboxylic acid-N,O)-silver(i) (UBEGOX).mop"
~/utilities/MOPAC_Batch.csh "(Cyclopentadienyl)-(18-crown-6)-rubidium dimethoxyethane solvate (QEXTIW).mop"
~/utilities/MOPAC_Batch.csh "(Cyclopentadienyl)-(o-phenylene-diamino)-cobalt (CAFJEY).mop"
~/utilities/MOPAC_Batch.csh "(Cyclopentadienyl)-chloro-beryllium (JEFKIO).mop"
~/utilities/MOPAC_Batch.csh "(Cyclopentadienyl-carboxylic acid)-(cyclopentadienyl-carboxylato)-cobalt(iii) (BOHRAR).mop"
~/utilities/MOPAC_Batch.csh "(Dibenzo-18-crown-S6)-ruthenium bis(hexafluorophosphate) nitromethane solvate (SIJVAI).mop"
~/utilities/MOPAC_Batch.csh "(Diethyl ether)-lithium heptamethyl-tungsten (RETNEJ).mop"
~/utilities/MOPAC_Batch.csh "(Diphenylmethanide)-(18-crown-6)-rubidium (UNIJIK).mop"
~/utilities/MOPAC_Batch.csh "(Ethylenediamine)-pyridine-trichloro-iridium(iii) (IBEFUR01).mop"
~/utilities/MOPAC_Batch.csh "(Ethylenediamine)-tetrahydroxy-germanium(iv) (NOHHIC).mop"
~/utilities/MOPAC_Batch.csh "(Hexafluoroacetylacetonato)-bis(trimethylphosphine)-silver (LEFWIC).mop"
~/utilities/MOPAC_Batch.csh "(Hexafluoroacetylacetonato)-trimethylphosphine-silver (LEFWEY).mop"
~/utilities/MOPAC_Batch.csh "(Nitrato-O)-bis(pyridine-4-carbonitrile-N)-silver(i) (FOHJIV).mop"
~/utilities/MOPAC_Batch.csh "(Oxybis((phenyliodanediyl)oxysulfonyloxy))bis(hydroxy(phenyl)iodane) (AHOREV).mop"
~/utilities/MOPAC_Batch.csh "(Pentamethyl-cyclopentadienyl)-tin tetrafluoroborate (PMCPSN10).mop"
~/utilities/MOPAC_Batch.csh "(Perfluoroisopropyl)oxonium (mu-2-fluoro)-bis(pentafluoro-antimonate) (GOBDEG).mop"
~/utilities/MOPAC_Batch.csh "(S)-2,2,2-Trifluoro-1-(9-anthryl)ethanol (SOCLIF).mop"
~/utilities/MOPAC_Batch.csh "(Tetra-azacyclotetradecane)-dichloro-diethyl-di-aluminium (JAXTUX).mop"
~/utilities/MOPAC_Batch.csh "(Trifluoromethylsulfonic acid-O)-pentafluoro-antimony (SOVWEF).mop"
~/utilities/MOPAC_Batch.csh "(Trimethylamine)-borane (ZZZVPE02).mop"
~/utilities/MOPAC_Batch.csh "(Z Z)-N N'-Dimethylurea (NIJHUJ).mop"
~/utilities/MOPAC_Batch.csh "(cryptand)-sodium tris(1,2,3-h-cycloocta-1,3,5-trienyl)-tantalum (OGISAY).mop"
~/utilities/MOPAC_Batch.csh "(h5-Cyclopentadienyl)-dichloro-oxo-vanadium(v) NIRKUU).mop"
~/utilities/MOPAC_Batch.csh "(h5-Cyclopentadienyl-carboxylic acid)-(h5-cyclopentadienyl-carboxylato)-cobalt(iii) (BOHRAR).mop"
~/utilities/MOPAC_Batch.csh "(mu-2-1,4,7,10-Tetra-azacyclododecane-1,4,7-triacetato-10-methyl hydrogen phosphonato)-triaqua-lithium-lutetium(iii) dihydrate (LARLAS).mop"
~/utilities/MOPAC_Batch.csh "(mu-2-2,6-bis(h5-Cyclopentadienylmethyl)pyridine)-bis(2,6-bis(h5-cyclopentadienylmethyl)pyridine-N)-di-yttrium dichloromethane solvate (CAWQAT).mop"
~/utilities/MOPAC_Batch.csh "(mu-2-Dibismuthide)-diammine-bis(18-crown-6)-di-cesium ammonia solvate (SAJROL).mop"
~/utilities/MOPAC_Batch.csh "(mu-2-Hydrogen 1H-imidazole-4,5-dicarboxylate-N,N')-bis(ammine)-di-silver(i) (DUKMOM01).mop"
~/utilities/MOPAC_Batch.csh "(mu-2-Oxo)-bis(difluoro-urea-antimony) (UROFSB10).mop"
~/utilities/MOPAC_Batch.csh "(mu-2-Oxo)-tetrakis(h5-cyclopentadienyl)-dimethyl-di-tungsten bis(hexafluorophosphate) (ZISMAP).mop"
~/utilities/MOPAC_Batch.csh "(mu-2-Phthalato-O,O')-diammine-di-silver(i) (RABVUL).mop"
~/utilities/MOPAC_Batch.csh "(mu-2-Propane-1,3-diamine)-dicyano-di-silver(i) (FILSOJ).mop"
~/utilities/MOPAC_Batch.csh "(mu-2-Pyrazine)-decafluoro-di-antimony (TUSBAK).mop"
~/utilities/MOPAC_Batch.csh "(mu-3-Ethylidyne)-tris((cyclopentadienyl)-nickel) (GINJIW).mop"
~/utilities/MOPAC_Batch.csh "(tetrachlorophthalato)-ammine-silver diammine-silver monohydrate (RIVTUM).mop"
~/utilities/MOPAC_Batch.csh "(tris(2-Aminoethyl)amine)-pyridine-copper(ii) diperchlorate (SELXIQ).mop"
~/utilities/MOPAC_Batch.csh "1 4 dioxocine 6-carboxylic acid chloride (CUWWIA).mop"
~/utilities/MOPAC_Batch.csh "1 4-Dimethoxyanthracene-9 10-dione (VICZAJ).mop"
~/utilities/MOPAC_Batch.csh "1 8-Bis(methoxy)anthraquinone (APUREI01).mop"
~/utilities/MOPAC_Batch.csh "1,2,3-Triaminoguanidine (FASGUB).mop"
~/utilities/MOPAC_Batch.csh "1,2,3-tris(trans-9-Octadecenoyl)glycerol (WISRAR).mop"
~/utilities/MOPAC_Batch.csh "1,2-bis(4-Pyridyl)ethane (ZEXKIW).mop"
~/utilities/MOPAC_Batch.csh "1,2-bis(Iodo)-1,2-diphospha-acenaphthene (GUTJOU).mop"
~/utilities/MOPAC_Batch.csh "1,3,5-Trinitro-1,3,5-triazacyclohexane (CTMTNA03).mop"
~/utilities/MOPAC_Batch.csh "1,3-Propylenediammonium selenite dihydrate (BAYCEK).mop"
~/utilities/MOPAC_Batch.csh "1,3-Propylenediammonium tetrachloro-manganese(ii) (PYDAMN03).mop"
~/utilities/MOPAC_Batch.csh "1,3-bis((Pyrid-2-ylamino)carbonyl)adamantane (RIZVOL).mop"
~/utilities/MOPAC_Batch.csh "1,3-bis((Pyrid-2-ylamino)carbonyl)adamantane a-ketoglutaric acid (RIZWUS).mop"
~/utilities/MOPAC_Batch.csh "1,3-bis(2-Furyl)azulene (GUDKAS).mop"
~/utilities/MOPAC_Batch.csh "1,3-di-t-butyl-2,4,5-triiodo-2,4,5-triphosphabicyclopentane iodine (BOCROB).mop"
~/utilities/MOPAC_Batch.csh "1,4-Dioxane dichloro-germanium (DIOXGC03).mop"
~/utilities/MOPAC_Batch.csh "1,4-Diselenane bis(iodine) (DSEIOD).mop"
~/utilities/MOPAC_Batch.csh "1,4-diazabicyclo[2.2.2]octane azelaic acid (UNEGEZ).mop"
~/utilities/MOPAC_Batch.csh "1,8-bis(tris(Dimethylamino)phosphoranylideneamino)naphthalene.mop"
~/utilities/MOPAC_Batch.csh "1-Dimethylamino-8-dimethylammonionaphthalene saccharin dihydrate (AJOHUC).mop"
~/utilities/MOPAC_Batch.csh "1-Ethyl-3-methylimidazolium hexafluoroniobate-(MESBIW).mop"
~/utilities/MOPAC_Batch.csh "1-Ethyl-3-methylimidazolium hexafluorotantalate (MESBOC).mop"
~/utilities/MOPAC_Batch.csh "1-Fluoro-2,8,9-trioxa-5-aza-1-germatricycloundecane (GAQMEQ01).mop"
~/utilities/MOPAC_Batch.csh "1-diazonia-4-azabicyclo[2.2.2]octane glutarate (UNEFIC).mop"
~/utilities/MOPAC_Batch.csh "1-ethyl-3-methylimidazolium hexafluoroantimonate (AQEYIE).mop"
~/utilities/MOPAC_Batch.csh "15-Crown-5 diaqua-tetrachloro-tin(iv) (FANRUH).mop"
~/utilities/MOPAC_Batch.csh "15-Crown-5 octa-aqua-lutetium trichloride (FILVUR).mop"
~/utilities/MOPAC_Batch.csh "15-Crown-5-sodium hexakis(phenylthiolato-S)-tantalum (KIGGEM).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6 aminosulfuric acid clathrate (SOVJOC).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6 hydroxonium clathrate aqua-oxo-tetrabromo-tungsten (NANQEY).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6 hydroxonium clathrate aqua-oxo-tetrachloro-molybdenum (JOKGOF01).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6 oxonium clathrate aqua-pentachloro-titanium (SEPJEC).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6 oxonium hexachloro-tantalum(v) (TEDYUW).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6 potassium dichloroaurate(i) (MUVTAY).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6 potassium tricarbonyl-tri-iodo-ruthenium (FEHGEE).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6 tetra-aqua-bis(isothiocyanato)-magnesium (FUYCAD).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6 trans-tetrafluoro-diaqua-silicon dihydrate (YORRIG01).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6-bis(hexafluoro-acetylacetonato)-strontium (QUGTIW).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6-cesium dicyano-silver(i) (GOKZOV).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6-dibromo-lead(ii) (RUMQEV).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6-dibromo-mercury(II) (POLKEG).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6-dichloro-lead(ii) (NOMJUV).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6-dichloro-mercury(II) (CESZOP).mop"
~/utilities/MOPAC_Batch.csh "18-Crown-6-oxonium hexafluoroniobate (SINSAK).mop"
~/utilities/MOPAC_Batch.csh "18-crown-6-di-iodo-mercury(ii) (DENZUR01).mop"
~/utilities/MOPAC_Batch.csh "18-crown-6-diiodo-lead(II) (TOJPIR).mop"
~/utilities/MOPAC_Batch.csh "2,2'-Bipyridinedi-ium tetrabromo-cobalt(ii) (BPYRBC11).mop"
~/utilities/MOPAC_Batch.csh "2,2'-Bipyridinedi-ium tetrabromo-zinc(ii) (AGEXAM).mop"
~/utilities/MOPAC_Batch.csh "2,2'-Bipyridyl potassium dicyano-gold(i) (PCAUPY).mop"
~/utilities/MOPAC_Batch.csh "2,2'-Dithenyl (DTENYL).mop"
~/utilities/MOPAC_Batch.csh "2,4,4,6,6-Pentachloro-2-(piperidyl)cyclotriphosphazene (POTKEO).mop"
~/utilities/MOPAC_Batch.csh "2,4,6-Trimethyl-2,4,6-triarsa-1,3,5-trithiacyclohexane (JEGDAA).mop"
~/utilities/MOPAC_Batch.csh "2,4,6-Trinitro-N-methyl-N-nitroaniline (Tetryl) (MTNANL).mop"
~/utilities/MOPAC_Batch.csh "2,8-dioxo-4,6-diphenyl-4-diioda-3,5,7-trioxanonane (AHORIZ).mop"
~/utilities/MOPAC_Batch.csh "2-(2-(3-Carboxypyridyl))-4-isopropyl-4-methyl-5-oxo-imidazole (JAZCOC01).mop"
~/utilities/MOPAC_Batch.csh "2-(4-pyridyl)malondialdehyde sesquihydrate (GIDLIP).mop"
~/utilities/MOPAC_Batch.csh "2-Amino-4-methylpyrimidine (XAQNUZ).mop"
~/utilities/MOPAC_Batch.csh "2-Chloro-1,3,6,2-trithia-arsocane (CTRTAS).mop"
~/utilities/MOPAC_Batch.csh "2-Chloro-1,3-dithia-2-stibacyclopentane (CLSSBP10).mop"
~/utilities/MOPAC_Batch.csh "2-Iodo-1,3-di-t-butyl-1,3,2-diazaphospholene (CORGAS).mop"
~/utilities/MOPAC_Batch.csh "2-Methylbenzoic acid (OTOLIC02).mop"
~/utilities/MOPAC_Batch.csh "2-Pyridone (PYRIDO04).mop"
~/utilities/MOPAC_Batch.csh "246-Tribromoaniline (BRANIL).mop"
~/utilities/MOPAC_Batch.csh "3,3'-Dithienyl ketone (DTHKET).mop"
~/utilities/MOPAC_Batch.csh "3,5-Dinitro-4-methylbenzoic acid (NOMBEA01).mop"
~/utilities/MOPAC_Batch.csh "3-Carboxyphenylammonium hydrogen 2,3-pyrazinedicarboxylate dihydrate (ZIKREQ).mop"
~/utilities/MOPAC_Batch.csh "3-Hydroxy-10,10-dimethyl-11-oxatricyclododeca-4,6-dien-8-one (LIGHIV).mop"
~/utilities/MOPAC_Batch.csh "3-Nitrobenzamide (JACYOB).mop"
~/utilities/MOPAC_Batch.csh "4,4'-Biphenol (DOHDPH02).mop"
~/utilities/MOPAC_Batch.csh "4,4'-Biphenol bis(caprolactam) (KEWZUI).mop"
~/utilities/MOPAC_Batch.csh "4,4'-Bipyridinedi-ium bis(chloro-trioxo-chromium(vi)) (HIHFOT).mop"
~/utilities/MOPAC_Batch.csh "4,4'-Bipyridinium tetrachloro-zinc (CIQXAB).mop"
~/utilities/MOPAC_Batch.csh "4,4'-Bipyridylium bis(mu-2-chloro)-tetrachloro-di-copper (BPYCCU).mop"
~/utilities/MOPAC_Batch.csh "4,4'-Bis(perfluorostyryl)stilbene (QERWUF).mop"
~/utilities/MOPAC_Batch.csh "4,5-bis(Dimethylamino)-1,8-dihydroxynaphthalene (RISBIE).mop"
~/utilities/MOPAC_Batch.csh "4,6-diphenyl-4l3,6l3-diioda-3,5,7-trioxa-2,8-dithianonane 2,2,8,8-tetraoxide (BACCUF).mop"
~/utilities/MOPAC_Batch.csh "4-(2,4-diisopropylphenyl)-4-oxo-2-butenoic acid.mop"
~/utilities/MOPAC_Batch.csh "4-(2,6-Dimethyl-4-N,N-diethylaminophenylimino)-3-methyl-1-phenyl-2-pyrazolin-5-one (MEPMPZ10).mop"
~/utilities/MOPAC_Batch.csh "4-(Dimethylamino)pyridinium hydrogen maleate (GUKVUE).mop"
~/utilities/MOPAC_Batch.csh "4-(Dimethylamino)pyridinium hydrogen phthalate (GUKVOY).mop"
~/utilities/MOPAC_Batch.csh "4-Aminobenzoic acid (AMBNAC04).mop"
~/utilities/MOPAC_Batch.csh "4-Aminobenzoic acid 4-nitroaniline (RILJEB).mop"
~/utilities/MOPAC_Batch.csh "4-Aminophenylacetic acid (FONGUL).mop"
~/utilities/MOPAC_Batch.csh "4-Dimethylaminopyridine (BUKJOG10).mop"
~/utilities/MOPAC_Batch.csh "4-Ethylpyridinium tetrabromoferrate(iii) (EPYMBF).mop"
~/utilities/MOPAC_Batch.csh "4-Fluoro-2-(phosphonomethyl)benzenesulfonic acid monohydrate (KIXQIR).mop"
~/utilities/MOPAC_Batch.csh "4-Hydroxybenzoic acid isonicotinamide (VAKTOR).mop"
~/utilities/MOPAC_Batch.csh "4-Iodo-tetramethyl-tetra-aza-phosphaspiroheptane-2,6-dione (SAKMUM).mop"
~/utilities/MOPAC_Batch.csh "4-Methyl-triphosphatricycloheptane (FATYUU).mop"
~/utilities/MOPAC_Batch.csh "4-Nitroaniline (NANILI22).mop"
~/utilities/MOPAC_Batch.csh "5-Formato uracil (POWBAF).mop"
~/utilities/MOPAC_Batch.csh "5H-dibenz(b,f)azepine-5-carboxamide saccharin solvate (UNEZAO).mop"
~/utilities/MOPAC_Batch.csh "6-(Pyran-4-one-2-yl)-1,4-dioxocine (CUWWEW).mop"
~/utilities/MOPAC_Batch.csh "7,7,14,4-Tetramethyldinaphtho-di-germanium (YIHWOB).mop"
~/utilities/MOPAC_Batch.csh "7-Methyl-1,3,5-triarsa-2,4,9-trithia-adamantane (MARSTA).mop"
~/utilities/MOPAC_Batch.csh "8-Azaguanine (AZGUAN01).mop"
~/utilities/MOPAC_Batch.csh "8-Azaguanine hydrate (AZGUAN).mop"
~/utilities/MOPAC_Batch.csh "9,10-Dihydroanthracene (DITBOX).mop"
~/utilities/MOPAC_Batch.csh "9-(2-Hydroxyethyl)adenine (FABFUJ).mop"
~/utilities/MOPAC_Batch.csh "Acetonitrile)-(tris((2-pyrazinyl)methyl)amine)-tri-iodo-lanthanum(iii) acetonitrile solvate (EFUBAI).mop"
~/utilities/MOPAC_Batch.csh "Acetonitrile-perfluoroisopropyl-silver (DUJXEL).mop"
~/utilities/MOPAC_Batch.csh "Acetophenone (ACETPH).mop"
~/utilities/MOPAC_Batch.csh "Acetylacetone (LIWPIQ01).mop"
~/utilities/MOPAC_Batch.csh "Acetylcholine (ACHOLC01).mop"
~/utilities/MOPAC_Batch.csh "Acetylide-octa-silver hexanitrate (SOVNEW01).mop"
~/utilities/MOPAC_Batch.csh "Aconitine (ACONTO10).mop"
~/utilities/MOPAC_Batch.csh "Adamantane (ADAMAN08).mop"
~/utilities/MOPAC_Batch.csh "Adamite (Zn2(AsO4)(OH)).mop"
~/utilities/MOPAC_Batch.csh "Adenosine (ADENOS11).mop"
~/utilities/MOPAC_Batch.csh "Adenosine-3'-phosphate dihydrate (ADPOSD).mop"
~/utilities/MOPAC_Batch.csh "Akermanite (Ca2MgSi2O7).mop"
~/utilities/MOPAC_Batch.csh "Albite ((NaAl)(Si3O8).mop"
~/utilities/MOPAC_Batch.csh "Alforsite (Ba5(PO4)3Cl).mop"
~/utilities/MOPAC_Batch.csh "Alpha Crystobalite (SiO2).mop"
~/utilities/MOPAC_Batch.csh "Alpha quartz (SiO2).mop"
~/utilities/MOPAC_Batch.csh "Alpha-Chitin.mop"
~/utilities/MOPAC_Batch.csh "Aluminite (Al2SO6 9(H2O)).mop"
~/utilities/MOPAC_Batch.csh "Aluminum (Al) (ICSD 64700).mop"
~/utilities/MOPAC_Batch.csh "Aluminum antimonide (AlSb).mop"
~/utilities/MOPAC_Batch.csh "Aluminum arsenide (AlAs).mop"
~/utilities/MOPAC_Batch.csh "Aluminum nitride (AlN).mop"
~/utilities/MOPAC_Batch.csh "Aluminum phosphide (AlP).mop"
~/utilities/MOPAC_Batch.csh "Aluminum sulfate (Al2(SO4)3) (ICSD 73249).mop"
~/utilities/MOPAC_Batch.csh "Aluminum tribromide (AlBr3).mop"
~/utilities/MOPAC_Batch.csh "Aluminum trichloride (AlCl3).mop"
~/utilities/MOPAC_Batch.csh "Aluminum trifluoride (AlF3).mop"
~/utilities/MOPAC_Batch.csh "Aluminum triiodide (AlI3).mop"
~/utilities/MOPAC_Batch.csh "Alunite (KAl3(SO4)2(OH)6).mop"
~/utilities/MOPAC_Batch.csh "Aminetrimethylborane (RIJHIB).mop"
~/utilities/MOPAC_Batch.csh "Aminoguanidinium hexa-bromo-copper(ii) (TIVJEN).mop"
~/utilities/MOPAC_Batch.csh "Ammine-(2,2'-bipyridine)-silver(i) nitrate (KUQPOC).mop"
~/utilities/MOPAC_Batch.csh "Ammine-(salicylaldehyde thiosemicarbazonato)-nickel(ii) (AMSCNI11).mop"
~/utilities/MOPAC_Batch.csh "Ammonia - boron trifluoride (NH3BF3) (ICSD 94885).mop"
~/utilities/MOPAC_Batch.csh "Ammonium aluminum EDTA dihydrate (WUCFIJ).mop"
~/utilities/MOPAC_Batch.csh "Ammonium aluminum sulfate ((NH4)Al(SO4)2 (12(H2O)).mop"
~/utilities/MOPAC_Batch.csh "Ammonium benzoate (YABFEO).mop"
~/utilities/MOPAC_Batch.csh "Ammonium bis(1,2-dicyanoethylene-1,2-dithiolato-S,S')-palladium monohydrate (SAHFOW).mop"
~/utilities/MOPAC_Batch.csh "Ammonium bromide (NH4Br) (ICSD 43300).mop"
~/utilities/MOPAC_Batch.csh "Ammonium chloride (NH4Cl).mop"
~/utilities/MOPAC_Batch.csh "Ammonium chromate ((NH4)2CrO4) (ICSD 1501451).mop"
~/utilities/MOPAC_Batch.csh "Ammonium chromium(III) alum ((NH4)Cr(SO4)2 12(H2O)).mop"
~/utilities/MOPAC_Batch.csh "Ammonium diaqua-oxo-bis(oxalato-O,O')-niobium(v) trihydrate (AMOXNB).mop"
~/utilities/MOPAC_Batch.csh "Ammonium dihydrogenphosphate (NH4 H2PO4).mop"
~/utilities/MOPAC_Batch.csh "Ammonium fluoride (NH4F).mop"
~/utilities/MOPAC_Batch.csh "Ammonium hexafluorosilicate (2(NH4)SiF6) (ICSD 1120016).mop"
~/utilities/MOPAC_Batch.csh "Ammonium hydrogen benzoate (AMHBZO).mop"
~/utilities/MOPAC_Batch.csh "Ammonium hydrogen phosphate ((NH4)2HPO4) (ICSD 2799).mop"
~/utilities/MOPAC_Batch.csh "Ammonium iodide (NH4I).mop"
~/utilities/MOPAC_Batch.csh "Ammonium nitrate (NH4NO3).mop"
~/utilities/MOPAC_Batch.csh "Ammonium nitrate 18-crown-6 (QOBJAS).mop"
~/utilities/MOPAC_Batch.csh "Ammonium perchlorate (NH4ClO4) (ICSD 40382).mop"
~/utilities/MOPAC_Batch.csh "Ammonium sulfate (2(NH4)SO4).mop"
~/utilities/MOPAC_Batch.csh "Ammonium trans-di-iodo-bis(glyoximato-N,N')-cobalt(iii) (KIDRIY).mop"
~/utilities/MOPAC_Batch.csh "Ammonium triiodide (NH4I3) (ICSD 2110220).mop"
~/utilities/MOPAC_Batch.csh "Ammonium tris(oxalato-O,O')-chromium(iii) dihydrate (AMOXCR).mop"
~/utilities/MOPAC_Batch.csh "Anatase (TiO2).mop"
~/utilities/MOPAC_Batch.csh "Andalusite (Al2SiO5).mop"
~/utilities/MOPAC_Batch.csh "Anglesite (PbSO4) (ICSD 109432).mop"
~/utilities/MOPAC_Batch.csh "Anhydrite (CaSO4).mop"
~/utilities/MOPAC_Batch.csh "Annabergite (Ni3(AsO4)2 8(H2O)).mop"
~/utilities/MOPAC_Batch.csh "Anthracene (ANTCEN14).mop"
~/utilities/MOPAC_Batch.csh "Anthracene photodimer (DPANTH03).mop"
~/utilities/MOPAC_Batch.csh "Antimony (Sb) (ICSD 651499).mop"
~/utilities/MOPAC_Batch.csh "Antimony sulfate (Sb2(SO4)3) (ICSD 618).mop"
~/utilities/MOPAC_Batch.csh "Antimony trichloride (SbCl3) (ICSD 8258).mop"
~/utilities/MOPAC_Batch.csh "Antimony(iii) bromide (SbBr3).mop"
~/utilities/MOPAC_Batch.csh "Antimony(iii) fluoride (SbF3).mop"
~/utilities/MOPAC_Batch.csh "Antimony(iii) iodide (SbI3).mop"
~/utilities/MOPAC_Batch.csh "Antimony(iii) trioxide (Sb4O6) (ICSD 16851).mop"
~/utilities/MOPAC_Batch.csh "Antimony(v) chloride (SbCl5).mop"
~/utilities/MOPAC_Batch.csh "Antimony(v) pentachloride (SbCl5) (ICSD 250363).mop"
~/utilities/MOPAC_Batch.csh "Antimony(v) pentoxide (Sb2O5) (ICSD 1422).mop"
~/utilities/MOPAC_Batch.csh "Apophyllite ((CaO)4 (SiO2)8 (H2O)8 KF).mop"
~/utilities/MOPAC_Batch.csh "Aqua titanium(III) EDTA hydrate ((YUCMAK).mop"
~/utilities/MOPAC_Batch.csh "Aqua-(1,4,7,10-tetrathiacyclododecane)-copper(ii) diperchlorate (CEFXAM).mop"
~/utilities/MOPAC_Batch.csh "Aqua-(4-chlorobenzoato-O)-silver(i) (RACZIF).mop"
~/utilities/MOPAC_Batch.csh "Aqua-(7,16-bis(2-O-hydroxyethyl-2-oxyethyl)-1,4,10,13-tetraoxa-7,16-diazacyclo-octadecane)-barium(ii) di-iodide dihydrate (VEPMUY).mop"
~/utilities/MOPAC_Batch.csh "Aqua-chloro-(15-crown-5)-iron(ii) oxonium tetrachloro-iron(ii) monohydrate (XEQGUV).mop"
~/utilities/MOPAC_Batch.csh "Aqua-chloro-(15-crown-5)-magnesium chloride acetonitrile solvate (YAFYEJ).mop"
~/utilities/MOPAC_Batch.csh "Aqua-tris(2-((dimethylamino)methyl)phenyl)borane (QEVYEV).mop"
~/utilities/MOPAC_Batch.csh "Aquamarine ((NaOH)(Al2O3)(BeO)3(SiO2)6).mop"
~/utilities/MOPAC_Batch.csh "Aragonite (CaCO3).mop"
~/utilities/MOPAC_Batch.csh "Arcanite (K2SO4).mop"
~/utilities/MOPAC_Batch.csh "Argon (Ar) (ICSD 77918).mop"
~/utilities/MOPAC_Batch.csh "Arkelite (ZrO2).mop"
~/utilities/MOPAC_Batch.csh "Arsenic (As) (ICSD 16516) hexagonal.mop"
~/utilities/MOPAC_Batch.csh "Arsenic (As) (ICSD 609832) orthorhombic.mop"
~/utilities/MOPAC_Batch.csh "Arsenic(iii) bromide (AsBr3).mop"
~/utilities/MOPAC_Batch.csh "Arsenic(iii) chloride (AsCl3).mop"
~/utilities/MOPAC_Batch.csh "Arsenic(iii) fluoride (AsF3).mop"
~/utilities/MOPAC_Batch.csh "Arsenic(iii) iodide (AsI3).mop"
~/utilities/MOPAC_Batch.csh "Arsenic(v) pentoxide (As2O5) (ICSD 987).mop"
~/utilities/MOPAC_Batch.csh "Aspartic acid (LASPRT).mop"
~/utilities/MOPAC_Batch.csh "Aspirin carbamazepine (TAZRAO).mop"
~/utilities/MOPAC_Batch.csh "Aspirin(I) ACSALA01.mop"
~/utilities/MOPAC_Batch.csh "Aspirin(II) (ACSALA13).mop"
~/utilities/MOPAC_Batch.csh "Atacamite (Cu2Cl(OH)3).mop"
~/utilities/MOPAC_Batch.csh "Azuleno-azulene (COLDEM).mop"
~/utilities/MOPAC_Batch.csh "Azurite ((CuO)3(CO2)2(H2O)).mop"
~/utilities/MOPAC_Batch.csh "B4Cl4 (ICSD 27872).mop"
~/utilities/MOPAC_Batch.csh "BH3NH3.mop"
~/utilities/MOPAC_Batch.csh "Ba(OH)2 3(H2O).mop"
~/utilities/MOPAC_Batch.csh "BaBrF.mop"
~/utilities/MOPAC_Batch.csh "BaCaAlF7.mop"
~/utilities/MOPAC_Batch.csh "BaFCl.mop"
~/utilities/MOPAC_Batch.csh "BaFI.mop"
~/utilities/MOPAC_Batch.csh "BaP2O6.mop"
~/utilities/MOPAC_Batch.csh "BaSbF5.mop"
~/utilities/MOPAC_Batch.csh "Barite (BaSO4).mop"
~/utilities/MOPAC_Batch.csh "Barium (Ba) (ICSD 108091) bcc.mop"
~/utilities/MOPAC_Batch.csh "Barium bromide dihydrate (BaBr2 2(H2O)) (ICSD 33949).mop"
~/utilities/MOPAC_Batch.csh "Barium chlorate (Ba(ClO3)2) (ICSD 40285).mop"
~/utilities/MOPAC_Batch.csh "Barium chloride dihydrate (BaCl2 2(H2O)) (ICSD 2254).mop"
~/utilities/MOPAC_Batch.csh "Barium chromate (BaCrO4) (ICSD 62560).mop"
~/utilities/MOPAC_Batch.csh "Barium cryptate(222) tetraselenide ethylenediamine solvate (BINDEH10).mop"
~/utilities/MOPAC_Batch.csh "Barium dibromide (BaBr2) (ICSD 15706).mop"
~/utilities/MOPAC_Batch.csh "Barium dichloride (BaCl2) (ICSD 15705).mop"
~/utilities/MOPAC_Batch.csh "Barium diiodide(BaI2) (ICSD 15707).mop"
~/utilities/MOPAC_Batch.csh "Barium ethylenediamine-tetra-acetate hydrate (BAEDTA).mop"
~/utilities/MOPAC_Batch.csh "Barium hexafluorosilicate (BaSiF6) (ICSD 201510).mop"
~/utilities/MOPAC_Batch.csh "Barium hydroxide (Ba(OH)2) (ICSD 56737).mop"
~/utilities/MOPAC_Batch.csh "Barium hydroxide (Ba(OH)2) (ICSD 92788).mop"
~/utilities/MOPAC_Batch.csh "Barium hydroxide octahydrate (BaO10H18).mop"
~/utilities/MOPAC_Batch.csh "Barium iodate (Ba(IO3)2) (ICSD 23276).mop"
~/utilities/MOPAC_Batch.csh "Barium nitrate (Ba(NO3)2) (ICSD 35495).mop"
~/utilities/MOPAC_Batch.csh "Barium nitrite (Ba(NO2)2) (ICSD 29510).mop"
~/utilities/MOPAC_Batch.csh "Barium oxalate oxalic acid dihydrate (BAHOXH11).mop"
~/utilities/MOPAC_Batch.csh "Barium oxide (BaO).mop"
~/utilities/MOPAC_Batch.csh "Barium sulfide (BaS) (ICSD 1210822).mop"
~/utilities/MOPAC_Batch.csh "Barium titanate (BaTiO3).mop"
~/utilities/MOPAC_Batch.csh "Barium tungstate (BaWO4) (ICSD 23702).mop"
~/utilities/MOPAC_Batch.csh "Barytocalcite (CaCa(CO3)2).mop"
~/utilities/MOPAC_Batch.csh "Basic beryllium acetate (Be4O(OOCCH3)6) (BEOACT).mop"
~/utilities/MOPAC_Batch.csh "Bayerite (Al(OH)3).mop"
~/utilities/MOPAC_Batch.csh "Benitoite ((BaO)(TiO2)(SiO2)3).mop"
~/utilities/MOPAC_Batch.csh "Benzene (BENZEN).mop"
~/utilities/MOPAC_Batch.csh "Benzo[c]phenanthrene (BZPHAN01).mop"
~/utilities/MOPAC_Batch.csh "Benzoic acid (BENZAC02).mop"
~/utilities/MOPAC_Batch.csh "Benzoylacrylic crystal structure.mop"
~/utilities/MOPAC_Batch.csh "Berberine sulfate (CISREB).mop"
~/utilities/MOPAC_Batch.csh "Berlinite (AlPO4).mop"
~/utilities/MOPAC_Batch.csh "Bertrandite ((BeO)4(SiO2)2(H2O).mop"
~/utilities/MOPAC_Batch.csh "Beryl ((Al2O3)(BeO)3(SiO2)6).mop"
~/utilities/MOPAC_Batch.csh "Beryllium (Be) hcp (ICSD 600013).mop"
~/utilities/MOPAC_Batch.csh "Beryllium catena-phosphate (BeP2O6) (ICSD 100404).mop"
~/utilities/MOPAC_Batch.csh "Beryllium chloride diethyl ether solvate (ETBECL).mop"
~/utilities/MOPAC_Batch.csh "Beryllium dibromide (BeBr2).mop"
~/utilities/MOPAC_Batch.csh "Beryllium dichloride (BeCl2).mop"
~/utilities/MOPAC_Batch.csh "Beryllium dichloride tetrahydrate (BeCl2 4(H2O)) ICSD 417642).mop"
~/utilities/MOPAC_Batch.csh "Beryllium difluoride (BeF2).mop"
~/utilities/MOPAC_Batch.csh "Beryllium diiodide (BeI2).mop"
~/utilities/MOPAC_Batch.csh "Beryllium hexaaluminate (BeAl6O10) (ICSD 95408).mop"
~/utilities/MOPAC_Batch.csh "Beryllium hydroxide (Be(OH)2) (ICSD 50445).mop"
~/utilities/MOPAC_Batch.csh "Beryllium oxide (BeO) (ICSD 391224).mop"
~/utilities/MOPAC_Batch.csh "Beryllium sulfate (BeSO4) (ICSD 44801).mop"
~/utilities/MOPAC_Batch.csh "Beryllium sulfate tetrahydrate (BeSO4 4(H2O)) (ICSD 23218).mop"
~/utilities/MOPAC_Batch.csh "Beryllium sulfide (BeS) (ICSD 616412).mop"
~/utilities/MOPAC_Batch.csh "Beta Tridymite (SiO2).mop"
~/utilities/MOPAC_Batch.csh "Beta quartz (SiO2).mop"
~/utilities/MOPAC_Batch.csh "Betainium hexafluoro-tantalum(iv) dihydrate (CEYCEO).mop"
~/utilities/MOPAC_Batch.csh "Biguanidinium hexafluoro-germanium (NEQFUL).mop"
~/utilities/MOPAC_Batch.csh "Biphenyl (BIPHEN04).mop"
~/utilities/MOPAC_Batch.csh "Biquanidinium hexachloro-copper(ii) dihydrate (FOWCUP).mop"
~/utilities/MOPAC_Batch.csh "Bis(1,4-Diazoniabicyclo(2.2.2)octane) bis(1-aza-4-azoniabicyclo(2.2.2)octane) tetrakis(tribromide) dibromide (DAHGUO).mop"
~/utilities/MOPAC_Batch.csh "[H(CH3OH)3(+)][CHB11Cl11(-)].mop"
~/utilities/MOPAC_Batch.csh "[H7O3(+)][CHB11Cl11(-)].mop"
~/utilities/MOPAC_Batch.csh "[H9O4(+)][CHB11Cl11(-)].mop"
~/utilities/MOPAC_Batch.csh "a,e-Diaminocapronic acid iodic acid (HIRMOK).mop"
~/utilities/MOPAC_Batch.csh "alpha Glycine.mop"
~/utilities/MOPAC_Batch.csh "alpha-Chitin (SUSGIW).mop"
~/utilities/MOPAC_Batch.csh "alpha-Ketoglutaric acid (COTPAC).mop"
~/utilities/MOPAC_Batch.csh "alpha-Lactose monohydrate (LACTOS10).mop"
~/utilities/MOPAC_Batch.csh "aqua-bis(hexafluoropentane-2,4-dione)-barium (KOWPOB).mop"
~/utilities/MOPAC_Batch.csh "bct-Carbon (C).mop"
~/utilities/MOPAC_Batch.csh "bct-Carbon P=20Gp (C).mop"
~/utilities/MOPAC_Batch.csh "beta Glycine.mop"
~/utilities/MOPAC_Batch.csh "beta-Alanine (BALNIN01).mop"
~/utilities/MOPAC_Batch.csh "beta-Alaninium EDTA-antimonate(iii) (BAWQIZ).mop"
~/utilities/MOPAC_Batch.csh "beta-Alaninium tetrachloro-iron(iii) (BALACF).mop"
~/utilities/MOPAC_Batch.csh "beta-Cellobiose (CELLOB04).mop"
~/utilities/MOPAC_Batch.csh "beta-D-Fructose (FRUCTO11).mop"
~/utilities/MOPAC_Batch.csh "beta-D-Galactose (BDGLOS01).mop"
~/utilities/MOPAC_Batch.csh "beta-Maltose monohydrate (MALTOS11).mop"
~/utilities/MOPAC_Batch.csh "bis((18-Crown-6)-rubidium) bis(mu-2-chloro)-tetrachloro-di-copper (JUMJEG).mop"
~/utilities/MOPAC_Batch.csh "bis((Cyclopentadienyl)-(dimethylphosphido)-cobalt) (DAFZAL).mop"
~/utilities/MOPAC_Batch.csh "bis((Hexa-ammine)-iridium(iii)) trioxalate tetrahydrate (XEDNID).mop"
~/utilities/MOPAC_Batch.csh "bis((h5-Cyclopentadienyl)-(mu-2-fluoro)-(pentafluoro-arsenic))-vanadium(iv) (VUFFIL).mop"
~/utilities/MOPAC_Batch.csh "bis((mu-2-Aqua)-hexa-aqua-calcium 5,5'-azotetrazolate) dihydrate (MINBOA).mop"
~/utilities/MOPAC_Batch.csh "bis((mu-2-Bromo)-2,2'-bipyridine-dibromo-bismuth(iii)) acetonitrile solvate (PURQAU).mop"
~/utilities/MOPAC_Batch.csh "bis((mu-2-Carbonyl)-(cyclopentadienyl)-nickel) (CBCNIB).mop"
~/utilities/MOPAC_Batch.csh "bis((mu-2-Chloro)-acetonitrile-chloro-copper(ii)) (DCUCAN).mop"
~/utilities/MOPAC_Batch.csh "bis((mu-2-Chloro)-trans-chloro-methyl-gallium) (ICOHIR).mop"
~/utilities/MOPAC_Batch.csh "bis((mu-2-Hydroxo)-bis(h5-cyclopentadienyl)-yttrium) diphenylacetylene (GAWLEV).mop"
~/utilities/MOPAC_Batch.csh "bis((mu-2-Methylamido)-dimethyl-gold(iii)) (DEVLUL).mop"
~/utilities/MOPAC_Batch.csh "bis((mu-2-N,N-diethylcarbamato-O,O,O')-bromo-bis(tetrahydrofuran)-magnesium) (HOYVUM).mop"
~/utilities/MOPAC_Batch.csh "bis((mu-2-Oxo)-(mu-2-trifluoroacetato-O,O')-trifluoro-antimony(v)) (OFAFSB01).mop"
~/utilities/MOPAC_Batch.csh "bis((mu-2-Tetrafluoroborato-F,F')-(nu-5-pentamethyl-cyclopentadienyl))-lead (VALVOT).mop"
~/utilities/MOPAC_Batch.csh "bis(1,1-Dimethylethylene-2,2-dithiolato-S,S')-copper(ii) (COYZOG).mop"
~/utilities/MOPAC_Batch.csh "bis(1,2,4-Triseleno-3,5-diazolium) bis(hexafluoroarsenate) (KAZBIW).mop"
~/utilities/MOPAC_Batch.csh "bis(1,2-Diammonioethane) hexabromo-rhodium(iii) bromide monohydrate (ZOKHEM).mop"
~/utilities/MOPAC_Batch.csh "bis(1,2-Ethylenediamine-N,N')-platinum(ii) dichloride (ZZZEDM02).mop"
~/utilities/MOPAC_Batch.csh "bis(1,4,7,10,13-Pentaoxacyclopentadecane)-barium bromide dihydrate (PXCDBA).mop"
~/utilities/MOPAC_Batch.csh "bis(1,4,7-Trithiacyclononane-S,S',S'')-ruthenium bis(trifluoromethanesulfonate) (FENDUX).mop"
~/utilities/MOPAC_Batch.csh "bis(1,4,7-Trithiacyclononane-S,S',S'')-technetium bis(tetrafluoroborate) acetonitrile solvate (WACXIH).mop"
~/utilities/MOPAC_Batch.csh "bis(1,4-bis(1-Azonia-3-azacyclohexen-2-yl)benzene) hexacyano-ruthenium(ii) octahydrate (WUGSEW01).mop"
~/utilities/MOPAC_Batch.csh "bis(2,2,2-Crypt-potassium) dithallium-ditellurium ethylenediamine solvate (BAKYIV).mop"
~/utilities/MOPAC_Batch.csh "bis(2,6-bis((Dimethylphosphino)methyl)phenyl)-magnesium benzene solvate (YESVIB).mop"
~/utilities/MOPAC_Batch.csh "bis(2-(Aminomethyl)pyridine-N,N')-silver(i) perchlorate (RAWTIT).mop"
~/utilities/MOPAC_Batch.csh "bis(2-(Ammoniomethyl)pyridinium) hexachloromanganate(ii) dihydrate (LIDQUL).mop"
