document.write("<a href=\"javascript:Jmol.script(jmolApplet0,'console')\">Console</a><br>")
document.write("<table align=\"left\" cellpadding=\"0\" cellspacing=\"0\" class=\"auto-style7\" style=\"width: 50%; \">")
document.write("			<tr>")
document.write("				<td class=\"auto-style6\" style=\"width: 45px\">&nbsp;</td>")
document.write("				<td class=\"auto-style6\" style=\"width: 36px\">Step 1</td>")
document.write("				<td class=\"auto-style6\">Step 2</td>")
document.write("				<td class=\"auto-style6\">Step 3</td>")
document.write("				<td class=\"auto-style6\">Step 4</td>")
document.write("				<td class=\"auto-style6\">Step 5</td>")
document.write("				<td class=\"auto-style6\">Step 6</td>")
document.write("			</tr>")
document.write("			<tr>")
document.write("				<td class=\"auto-style3\" style=\"width: 45px\">Step 1</td>")
document.write("				<td class=\"auto-style3\" style=\"width: 36px\">")
document.write("				<a href=\"Step_1_Chymotrypsin_starting_model.html\">")
document.write("				<img height=\"14\" src=\"blue_dot.gif\" width=\"14\" align=\"middle\"></a></td>")
document.write("				<td class=\"auto-style3\">&nbsp;</td>")
document.write("				<td class=\"auto-style3\">&nbsp;</td>")
document.write("				<td class=\"auto-style3\">&nbsp;</td>")
document.write("				<td class=\"auto-style3\">&nbsp;</td>")
document.write("				<td class=\"auto-style3\">&nbsp;</td>")
document.write("			</tr>")
document.write("			<tr>")
document.write("				<td class=\"auto-style5\" style=\"width: 45px\">Step 2</td>")
document.write("				<td class=\"auto-style5\" style=\"width: 36px\">")
document.write("				<a href=\"Step_1_2_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"blue_dot.gif\" width=\"14\" align=\"middle\"></a></td>")
document.write("				<td class=\"auto-style5\">")
document.write("				<a href=\"Step_2_Chymotrypsin_Tetrahedral_complex_His57_ionized.html\">")
document.write("				<img height=\"14\" src=\"blue_dot.gif\" width=\"14\" align=\"middle\"></a></td>")
document.write("				<td class=\"auto-style5\">&nbsp;</td>")
document.write("				<td class=\"auto-style5\">&nbsp;</td>")
document.write("				<td class=\"auto-style5\">&nbsp;</td>")
document.write("				<td class=\"auto-style5\">&nbsp;</td>")
document.write("			</tr>")
document.write("			<tr>")
document.write("				<td class=\"auto-style5\" style=\"width: 45px\">Step 3</td>")
document.write("				<td class=\"auto-style5\" style=\"width: 36px\">")
document.write("				<a href=\"Step_1_3_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"red_dot.gif\" width=\"14\" align=\"middle\"></a></td>")
document.write("				<td class=\"auto-style5\">")
document.write("				<a href=\"Step_2_3_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"blue_dot.gif\" width=\"14\" align=\"middle\"></a></td>")
document.write("				<td class=\"auto-style5\">")
document.write("				<a href=\"Step_3_Chymotrypsin_tetrahedral_intermediate.html\">")
document.write("				<img height=\"14\" src=\"blue_dot.gif\" width=\"14\" align=\"middle\"></a></td>")
document.write("				<td class=\"auto-style5\">&nbsp;</td>")
document.write("				<td class=\"auto-style5\">&nbsp;</td>")
document.write("				<td class=\"auto-style5\">&nbsp;</td>")
document.write("			</tr>")
document.write("			<tr>")
document.write("				<td class=\"auto-style5\" style=\"width: 45px\">Step 4</td>")
document.write("				<td class=\"auto-style5\" style=\"width: 36px\">")
document.write("				<a href=\"Step_1_4_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"red_dot.gif\" width=\"14\" align=\"middle\"></a></td>")
document.write("				<td class=\"auto-style5\">")
document.write("				<a href=\"Step_2_4_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"red_dot.gif\" width=\"14\" align=\"middle\" class=\"auto-style9\"></a></td>")
document.write("				<td class=\"auto-style5\">")
document.write("				<a href=\"Step_3_4_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"blue_dot.gif\" width=\"14\" align=\"middle\" class=\"auto-style9\"></a></td>")
document.write("				<td class=\"auto-style5\">")
document.write("				<a href=\"Step_4_Chymotrypsin_C-N_Separated.html\">")
document.write("				<img height=\"14\" src=\"blue_dot.gif\" width=\"14\" align=\"middle\"></a></td>")
document.write("				<td class=\"auto-style5\">&nbsp;</td>")
document.write("				<td class=\"auto-style5\">&nbsp;</td>")
document.write("			</tr>")
document.write("			<tr>")
document.write("				<td class=\"auto-style5\" style=\"width: 45px\">Step 5</td>")
document.write("				<td class=\"auto-style5\" style=\"width: 36px\">")
document.write("				<a href=\"Step_1_5_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"red_dot.gif\" width=\"14\" align=\"middle\" class=\"auto-style9\"></a></td>")
document.write("				<td class=\"auto-style5\">")
document.write("				<a href=\"Step_2_5_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"red_dot.gif\" width=\"14\" align=\"middle\" class=\"auto-style9\"></a></td>")
document.write("				<td class=\"auto-style5\">")
document.write("				<a href=\"Step_3_5_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"red_dot.gif\" width=\"14\" align=\"middle\" class=\"auto-style9\"></a></td>")
document.write("				<td class=\"auto-style5\">")
document.write("				<a href=\"Step_4_5_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"blue_dot.gif\" width=\"14\" align=\"middle\" class=\"auto-style9\"></a></td>")
document.write("				<td class=\"auto-style5\">")
document.write("				<a href=\"Step_5_Chymotrypsin_pre_acid.html\">")
document.write("				<img height=\"14\" src=\"blue_dot.gif\" width=\"14\" align=\"middle\"></a></td>")
document.write("				<td class=\"auto-style5\">&nbsp;</td>")
document.write("			</tr>")
document.write("			<tr>")
document.write("				<td class=\"auto-style8\" style=\"width: 45px\">Step 6</td>")
document.write("				<td class=\"auto-style8\" style=\"width: 36px\">")
document.write("				<a href=\"Step_1_6_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"red_dot.gif\" width=\"14\" align=\"middle\" class=\"auto-style9\"></a></td>")
document.write("				<td class=\"auto-style8\">")
document.write("				<a href=\"Step_2_6_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"red_dot.gif\" width=\"14\" align=\"middle\" class=\"auto-style9\"></a></td>")
document.write("				<td class=\"auto-style8\">")
document.write("				<a href=\"Step_3_6_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"red_dot.gif\" width=\"14\" align=\"middle\" class=\"auto-style9\"></a></td>")
document.write("				<td class=\"auto-style8\">")
document.write("				<a href=\"Step_4_6_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"red_dot.gif\" width=\"14\" align=\"middle\" class=\"auto-style9\"></a></td>")
document.write("				<td class=\"auto-style8\">")
document.write("				<a href=\"Step_5_6_Transition_state.html\">")
document.write("				<img height=\"14\" src=\"blue_dot.gif\" width=\"14\" align=\"middle\" class=\"auto-style9\"></a></td>")
document.write("				<td class=\"auto-style8\">")
document.write("				<a href=\"Step_6_Chymotrypsin_ester_hydrolyzed.html\">")
document.write("				<img height=\"14\" src=\"blue_dot.gif\" width=\"14\" align=\"middle\"></a></td>")
document.write("			</tr>")
document.write("		</table>")
