      SUBROUTINE CALVK(QCM2)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INCLUDE 'KEYS.i'
      INCLUDE 'SIZES.i'
      COMMON /MLKSTI/ NUMAT,NAT(NUMATM),NFIRST(NUMATM),NMIDLE(NUMATM),
     1                NLAST(NUMATM), NORBS, NELECS,NALPHA,NBETA,
     2                NCLOSE,NOPEN,NDUMY
      COMMON /BORN  / BP(NUMATM),FGB(NPACK),CCT1,ZEFF(NUMATM),
     1                QEFF2(NUMATM),DRVPOL(MPACK)
      COMMON /SOLVCM/ CELEID,SLVRAD,SLVRD2,CSSIGM    
      COMMON /SCRFVK/VK(NUMATM)
      DIMENSION QCM2(*)
      DATA ZERO /0D0/
C
C     CALCULATE REACTION FILED AT EACH ATOM
C
C
      DO 100 I=1,NUMAT
      VK(I)=0.0
      DO 200 J=1,I
      IJ=I*(I-1)/2+J
  200 VK(I)=VK(I)+QCM2(J)*(FGB(IJ))
      DO 210 J=I+1,NUMAT
      IJ=J*(J-1)/2+I
C Note Dielectric constant is already factored into FGB
  210 VK(I)=VK(I)+QCM2(J)*(FGB(IJ))
  100 CONTINUE
      RETURN
      END
