      SUBROUTINE ECRIT (BARAT) 
      IMPLICIT DOUBLE PRECISION (A-H,O-Z) 
       INCLUDE 'SIZES.i'
       INCLUDE 'FFILES.i'                                               GDH1095
C 
C      SADDLE POINT/CHAIN... 
C     PRINTOUT AT EACH ITERATION (CONTROLED BY IMP) 
C 
      COMMON /OPTIMI / IMP,IMP0                                         3GL3092
      COMMON /OPTMCI / ISTAB,IJUMP,IROTH,NVAR,ITEG,IBRCH,               3GL3092
     1                 INDI(NCHAIN,2),NP1,ITE,KK,JVOIS,ITEST,MM,        3GL3092
     2                 ITETOT,N,LIMIT,IS,NLR(2),NT                      3GL3092
      COMMON /OPTMCL / FAIL,IBID,FLAG,FLACHN(NCHAIN+1)                  GCL0892 
      COMMON /OPTMCR / H(MAXHES),GNEW(MAXPAR),XNEW(MAXPAR),ENEW,        3GL3092
     1                GOLD(MAXPAR),XOLD(MAXPAR),EOLD,QDER,DMAX,         3GL3092
     2                COSDIR(MAXPAR,2),TRANS1(MAXPAR),HAUT(MAXPAR+2),   3GL3092
     3                DIR(MAXPAR),EIGEN(MAXPAR),R(2),EPS1,COSTET,Q,D,   3GL3092
     4                D1,D2,D3,D4,D5,D6,D7,D8,D9,CORREL,PIGI,GIGI,      3GL3092
     5                XVAR(MAXPAR,MAXPAR),GVAR(MAXPAR,MAXPAR),          3GL3092 
     6                HVEC(MAXPAR,4),THR1,THR2,COORD(MAXPAR+1,NCHAIN),  3GL3092 
     7                X(MAXPAR),F,G(MAXPAR),EPS,DELTAE,                 3GL3092 
     8                RDUMY(MAXPAR*MAXPAR)                              3GL3092
C     COMMON /OPTIM/ IMP,IMP0,LEC,IPRT,H(MAXHES),GNEW(MAXPAR) 
C    .              ,XNEW(MAXPAR),ENEW,GOLD(MAXPAR),XOLD(MAXPAR),EOLD 
C    .              ,QDER,DMAX,COSDIR(MAXPAR,2),TRANS1(MAXPAR) 
C    .              ,HAUT(MAXPAR+2),DIR(MAXPAR),EIGEN(MAXPAR),R(2),EPS1 
C    .              ,COSTET,Q,D,D1,D2,D3,D4,D5,D6,D7,D8,D9,CORREL,PIGI 
C    .              ,GIGI,XVAR(MAXPAR,MAXPAR),GVAR(MAXPAR,MAXPAR) 
C    .              ,HVEC(MAXPAR,4),THR1,THR2,COORD(MAXPAR+1,NCHAIN) 
C    .              ,X(MAXPAR),F,G(MAXPAR),EPS,DELTAE 
C    .              ,ISTAB,IJUMP,IROTH,NVAR,ITEG,IBRCH,INDI(NCHAIN,2) 
C    .              ,NP1,ITE,KK,JVOIS,ITEST,MM,ITETOT 
C    .              ,N,LIMIT,IS,NLR(2),NT,FAIL,IBID,FLAG,FLACHN(NCHAIN) 
      CHARACTER*6 BARAT(2)                                              GCL0393
      LOGICAL FAIL,IBID,FLAG,FLACHN 
       SAVE
C 
C     GENERAL INFORMATION 
      GG=HAUT(N+2)**2 
      RMS=HAUT(N+2)/SQRT(DBLE(N))                                       GCL0393
      WRITE (JOUT,200) ITE,ENEW,RMS,GG,MM,(BARAT(I),NLR(I),I=1,2) 
      IF(IMP.LT.2) RETURN 
C     COORDINATES AND GRADIENT AT THE HIGHEST POINT 
      WRITE(JOUT,150) (XNEW(I),I=1,N) 
      WRITE(JOUT,100) (GNEW(I),I=1,N) 
      IF(IMP.LT.3.OR.MM.LT.0) GO TO 21 
C     ESTIMATED SECOND DERIVATIVES 
      WRITE(JOUT,301) 
      MI=MIN(MM+1,4,N)                                                  GCL0393
      DO 20 I=1,MI 
   20 WRITE(JOUT,300) I,EIGEN(I),(HVEC(J,I),J=1,N) 
   21 IF(IMP.LT.4) RETURN 
C     CHAIN OF POINTS 
      DO 10   J=1,2 
      WRITE(JOUT,500) BARAT(J),NLR(J) 
      IFIN = NLR(J) 
      DO 10  I=1,IFIN 
      K=INDI((J-1)*(IFIN+1)+(3-2*J)*I,J) 
   10 WRITE (JOUT,400 ) COORD(NP1,K),(COORD(L,K),L=1,N) 
      RETURN 
C 
  100 FORMAT(' GRADIENT    :',6F10.5/(14X,6F10.5)) 
  150 FORMAT(' COORDINATES :',6F10.5/(14X,6F10.5)) 
  200 FORMAT('0ITERATION',I5,1X,'HIGH POINT...ENERGY:',1PD16.8,3X, 
     1 'RMS GRAD.:',D8.2/' <G!G>=',D12.6,5X,'INDEX:',I4,3X, 
     2 'CHAIN LENGTH...',2(A6,':',I2)) 
  300 FORMAT(I3,1P,D13.5,' ... ',0P,7F8.4,/,(21X,7F8.4)) 
  301 FORMAT(' ESTIMATED EIGENVALUES AND EIGENVECTORS OF THE HESSIAN ') 
  500 FORMAT(A6,' CHAIN ','LENGTH:',I3,5X,'ENERGY AND COORDINATES(A,RAD) 
     1 ...') 
  400 FORMAT(1P,D15.7,' ...',5D12.4,/(19X,5D12.4)) 
      END 
