      SUBROUTINE KFINIT
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INCLUDE 'KEYS.i'
C******************************************************************************
C
C    THIS SUBROUTINE INITIALIZES ALL THE KEYWORD FLAGS AND ASSOCIATED VALUES
C
C    CREATED BY DJG 0995
C
C******************************************************************************
      ICM2=0                                                            GDH0997
      ICM3=0                                                            !JT0802
      ISM52R=0                                                          GDH0997
      ISM54R=0                                                          GDH0997
      ICART=0                                                           GDH0496
      ICIS=0                                                            DL0397
      IPDS5U=0                                                          DJG0496
      IPDS5A=0                                                          GDH0496
      IPDS5P=0                                                          GDH0496
      IS5A2P=0                                                          GDH0596
      IS5P2P=0                                                          GDH0596
      ISM5U=0                                                           DJG0496
      ISM5A=0                                                           CCC0496
      ISM5P=0                                                           CCC0496
      ISM50=0                                                           GDH0696
      IFEHAL=0                                                          GDH0797
      IFACAR=0                                                          GDH0797
      ISM505=0                                                          GDH0597
      ITGO=0                                                            GDH0597
      ISM4=0
      ISM21=0
      ISM31=0
      ISM22=0
      ISM23=0
      ISM2=0
      ISM3=0
      ISM1=0
      ISM1A=0
      IIOFR=0                                                           DJG0396
      IALPHA=0                                                          DJG0396
      IBETA=0                                                           DJG0396
      IGAMMA=0                                                          DJG0396
      ICS1=0
      ICS2=0
      ICS3=0
      ISCFCR=0
      IGCOMP=0
      IGNORM=0
      IPRECI=0
      IPULAY=0
      ICAMPK=0
      ISHIFT=0
      IFULSC=0
      IFAIL=0
      IITRY=0
      IFORWR=0
      INEWTO=0
      IPOWEL=0
      IBFGS=0
      IDFP=0
      IEFOLL=0
      ITSTAT=0
      ISIGMA=0
      INLLSQ=0
      ILTRD=0
      ISADDL=0
      ICHAIN=0
      ITRUSG=0                                                          DJG0496
      ITRUSE=0                                                          DJG0496
      IOPT=0
      I0SCF=0
      I1SCF=0
      IGEOOK=0
      INOPOL=0
      IFORCE=0
      ITHERM=0
      IROT=0
      ITRANS=0
      ISTEP1=0
      ISTEP2=0
      IMULLI=0
      IPISIG=0
      IENPAR=0
      IPOLAR=0
      IPATH=0
      IWEIGH=0
      ITV=0
      IPRINT=0
      IDEBUG=0
      IDEBUP=0
      IFLEPO=0
      IFMAT=0
      IITER=0
      ICOMPF=0
      IDERI1=0
      IDERI2=0
      IDERIV=0
      IHCORE=0
      ILINMI=0
      ILOCMI=0
      IMOLDA=0
      IPOWSQ=0
      IDCART=0
      IEIGS=0
      IPLITE=0
      ISEARC=0
      ITIMES=0
      IINTER=0
      IDENMA=0
      IDENOU=0
      IDENSI=0
      IDFORC=0
      IEXTER=0
      ISPART=0                                                          DJG0496
      IFOCK=0
      IGRADI=0
      IGRAPH=0
      IISOTO=0
      ILOCAL=0
      IMECI=0
      INOINT=0
      INOXYZ=0
      IOLDEN=0
      IOLDMA=0
      IVECTO=0
      IBONDS=0
      I1ELEC=0
      INOREF=0
      IDFPSA=0
      IDEP=0
      ISPIN=0
      IINPUT=0
      INOINP=0
      ICI=0
      IROOT=0
      IMICRO=0
      IUHF=0
      IOPEN=0
      ISINGL=0
      IDOUBL=0
      ITRIPL=0
      IQUART=0
      IQUINT=0
      ISEXTE=0
      IBIRAD=0
      IEXCIT=0
      IFILL=0
      IESR=0
      IHYPER=0
      IAM1=0
      IPM3=0
      IMNDOC=0
      IMINDO=0
      IMNDO=0
      IDRC=0
      IKINET=0
      IHPRIO=0
      ITPRIO=0
      IXPRIO=0
      ISOLVN=0
      IMSURF=0
      IDIELE=0
      ISVCDR=0
      ISVCSR=0
      INOCOG=0
      IEXTSM=0
      IEXTCM=0
      IEXTM=0
      ISTDM=0
      IXKW=0
      IRESTA=0
      ICYCLE=0
      ITLIMI=0
      ITDUMP=0
      IDERIN=0
      IDERIS=0
      ISYMME=0
      IXYZ=0
      IKICK=0
      ILET=0
      ICHARG=0
      ITRUES=0
      IHF=0
      IHFCAL=0                                                          GDH1/96
      IGAS=0                                                            GDH1/96
      IGPGCD=0                                                          GDH1/96
      IBAR=0
      IDEV=0
      IVOLUM=0
      INOVOL=0
      ICM1=0
      IAREAS=0
      IDEPVA=0
      INONR=0
      IHESS=0
      IMODE=0
      IRSCAL=0
      IDMAX=0
      IOMIN=0
      IRMIN=0
      IRMAX=0
      IDDMAX=0
      IDDMIN=0
      IRECAL=0
      IIUPD=0
      IGNMIN=0
      IDOTS=0
      IGEPOL=0
      IRAD1=0
      ITEXPN=0
      INDIVC=0
      INDIVE=0
      INDOTC=0
      INDOTE=0
      IASA=0
      ITONE=0
      FIHF=0.0D0
      FISCFC=0.0D0
      FIGCOM=0.0D0
      FIGNOR=0.0D0
      FISHIF=0.0D0
      FISTE1=0.0D0
      FISTE2=0.0D0
      FIDRC=0.0D0
      FIKINE=0.0D0
      FIMSUR=0.0D0
      FIDIEL=0.0D0
      FISVCD=0.0D0
      FISVCS=0.0D0
      FIIOFR=0.0D0                                                      DJG0396
      FIALPH=0.0D0                                                      DJG0396
      FIBETA=0.0D0                                                      DJG0396
      FIGAMM=0.0D0                                                      DJG0396
      FIBAR=0.0D0
      FIDEPV=0.0D0
      FIDMAX=0.0D0
      FIOMIN=0.0D0
      FIRMIN=0.0D0
      FIRMAX=0.0D0
      FIDDMA=0.0D0
      FIDDMI=0.0D0
      FITEXP=0.0D0
      FITONE=0.0D0
      FIHPRI=0.0D0
      FITPRI=0.0D0
      FIXPRI=0.0D0
      FITLIM=0.0D0
      FITDUM=0.0D0
      IIIUPD=0
      IIROT=0
      IIPRIN=0
      IICI=0
      IIROOT=0
      IIMICR=0
      IIOPE1=0
      IIOPE2=0
      IIFILL=0
      IICYCL=0
      IIKICK=0
      IICHAR=0
      IIHESS=5                                                          1203BL04
C     The default hessian is calculated with LINDH instead of diagonal  1203BL04
      IIMODE=0
      IIRECA=0
      IIDIVC=0
      IIDIVE=0
      IIDOTC=0
      IIDOTE=0
      IITHE1=0
      IITHE2=0
      IITHE3=0
      IIRAD=0
      IIITRY=0
      CIEXTE='                    '
      CISOLV='       '                                                  DJG0297
      IPRGEO=0                                                          PDW1199
      IPRCOU=0                                                          PDW1199
      IPRRAD=0                                                          PDW1199
      IPRPOL=0                                                          PDW1199
      RETURN
      END
