      SUBROUTINE LDATA(NOPT,IOPT1,ITERAT,N,LIMIT,EPS,IND)               DJG0995
      IMPLICIT DOUBLE PRECISION (A-H,O-Z) 
       INCLUDE 'SIZES.i'
       INCLUDE 'FFILES.i'                                               GDH1095
      COMMON /OPTIMI / IMP,IMP0                                         3GL3092
      COMMON /OPTMCR / HNEW(MAXHES),GNEW(MAXPAR),                       3GL3092 
     1                 P(MAXPAR*MAXPAR),STEP(MAXPAR),SEUIL(2),          3GL3092 
     2                 ESTIM(3),PMIN(3),PMAX(3),EG(3),                  3GL3092 
     3                 RDUMY(MAXPAR*(2*MAXPAR+NCHAIN+14) + 15 + NCHAIN) 3GL3092
      COMMON /PRECI/ SCFCV,SCFTOL,EGDUM(9),KTYP(MAXPAR) 
      DIMENSION PAS(3)                                                  GCL0393
      CHARACTER*8 DERI(2),DERIV(2),DER                                  GCL0393
       SAVE
C     REFERENCE RELATIVE ERROR ON HESSIAN DIAGONAL ELEMENTS 
C               ACCORDING TO IOPT1 OPTION :                             DJG0995
      DATA REL1,REL2 
     1/1.D-1,1.D-2/ 
      DATA DERI /' ONESTEP',' TWOSTEP'/,DERIV /'ANAL-NUM','NUM-NUM '/   GCL0393
C 
      SEUIL(1)=REL1 
      SEUIL(2)=REL2 
C 
C     ESTABLISH REFERENCE STEPS FOR HESSIAN MATRIX EVALUATION 
C     EG      : ESTIMATE OF ABSOLUTE ERROR ON GRADIENT COMPONENTS 
C     ESTIM   : ESTIMATE OF HESSIAN DIAGONAL ELEMENTS 
C               (USUAL ORDER OF MAGNITUDE) 
C     REL1,2  : WISHED RELATIVE ERROR ACCORDING TO IOPT1 OPTION         DJG0995
C     PMAX    : MAXIMUM ALLOWED INCREMENT LENGTH IN ALL CASE 
      GO TO (10,15),IOPT1                                               DJG0995 
   10 IF (IND.EQ.7) GO TO 12 
      DO 11 I=1,3 
   11 PAS(I)=MIN(PMAX(I),MAX(PMIN(I),3.D0*(EG(I)+SQRT( 
     . EG(I)**2+0.67D0*REL1*SCFCV*ESTIM(I)))/(REL1*ESTIM(I)))) 
      GO TO 20 
   12 DO 13 I=1,3 
   13 PAS(I)=MIN(PMAX(I),MAX(PMIN(I),SQRT(SCFCV*2.D0/(REL1*ESTIM(I))))) 
      GO TO 20 
   15 DO 16 I=1,3 
      PMAX(I)=1.4D0*PMAX(I) 
   16 PAS(I)=MIN(PMAX(I),MAX(PMIN(I),EG(I)/(ESTIM(I)*REL2))) 
C     COMPLETE INITIALIZATION 
   20 DER=DERIV(1) 
      IF(IND.GT.6) DER=DERIV(2) 
      EPSMAX=0.D0 
      DO 21 I=1,N 
      STEP(I)=PAS(KTYP(I)) 
   21 EPSMAX=EPSMAX+EG(KTYP(I))**2 
      EPS=MAX(EPS,5.D0*SQRT(EPSMAX/DBLE(N)))                            GCL0393
      IF (IND.EQ.5.OR.IND.EQ.7) GO TO 22 
      NOPT=11 
      WRITE(JOUT,101) N,LIMIT,DERI(IOPT1),DER,EPS                       DJG0995
      WRITE(JOUT,104) SCFCV,EG,PMAX,PMIN 
      RETURN 
   22 WRITE(JOUT,102) N,LIMIT,DERI(IOPT1),DER,EPS                       DJG0995
      WRITE(JOUT,104) SCFCV,EG,PMAX,PMIN 
      NOPT=2 
      RETURN 
  101 FORMAT(//' CRITICAL POINT RESEARCH IN',I3,' VARIABLES', 
     . 2X,'ITE MAX:',I4/ 
     .' SECOND DERIVATIVES BY THE',A8,' METHOD  (',A8,')'/ 
     .' REQUIRED CONVERGENCE ON RMS GRADIENT',1PD9.1) 
  102 FORMAT(//' MINIMIZATION IN',I3,' VARIABLES', 
     . 2X,'ITE MAX:',I4/ 
     .' SECOND DERIVATIVES BY THE',A8,' METHOD  (',A8,')'/ 
     .' REQUIRED CONVERGENCE ON RMS GRADIENT',1PD9.1) 
  104 FORMAT(' ERROR ON ENERGY     :',1P,D10.2/7X,'ON DERIVATIVES:', 
     . 3D10.2/' LARGEST ALLOWED STEP:',0P,3F10.6 
     . /' LOWEST  ALLOWED STEP:',3F10.6) 
      END 
