      SUBROUTINE MECID ( EIGS,GSE,EIGA,DIAG)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INCLUDE 'SIZES.i'
      DIMENSION EIGS(*),EIGA(*),DIAG(*)
      COMMON /BASEOC/ OCCA(NMECI),KDUM(NMECI+2)
     1       /XYIJKL/ XY(NMECI,NMECI,NMECI,NMECI)
     2       /CIDATA/ VECTCI(MAXCI),XX,NELEC,NMOS,LAB                   DL0397
     3               ,NALPHA(MAXCI)                                     DL0397
     4               ,MICROA(NMECI,MAXCI),MICROB(NMECI,MAXCI)           DL0397
C 
C     EIGENVALUES AFTER REMOVAL OF 2-ELECT INTERACTION : EIGA 
C     GROUND STATE (VACUUM) ENERGY : GSE 
C     DIAGONAL ELEMENTS OF THE C.I.MATRIX : DIAG 
C 
       SAVE
      GSE=0.D0
      DO 20 I=1,NMOS
      X=0.0
      DO 10 J=1,NMOS
   10 X=X+(2.D0*XY(I,I,J,J)-XY(I,J,I,J))*OCCA(J)
      EIGA(I)=EIGS(I+NELEC)-X
      GSE=GSE+EIGA(I)*OCCA(I)*2.D0
      GSE=GSE+XY(I,I,I,I)*OCCA(I)*OCCA(I)
      DO 20 J=I+1,NMOS
   20 GSE=GSE+2.D0*(2.D0*XY(I,I,J,J) - XY(I,J,I,J))*OCCA(I)*OCCA(J)
C     DIAGONAL ELEMENTS OF C.I MATRIX 
      DO 30 I=1,LAB
   30 DIAG(I)=DIAGI(MICROA(1,I),MICROB(1,I),EIGA,XY,NMOS)-GSE
      RETURN
      END

